# Generated by Django 4.2.1 on 2023-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_ToursAPP", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="substop",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
