# Generated by Django 4.2.1 on 2023-06-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StopAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/stop_audio")),
                ("script", models.TextField(default="")),
                ("is_stop_main", models.BooleanField(default=False)),
                ("is_sub_main", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StopImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/stop_images")),
                ("caption", models.CharField(default="", max_length=255)),
                ("is_stop_main", models.BooleanField(default=False)),
                ("is_sub_main", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StopVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="video/stop_video")),
                ("description", models.TextField(default="")),
                ("script", models.TextField(default="")),
                ("is_stop_main", models.BooleanField(default=False)),
                ("is_sub_main", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TourAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/tour_audio")),
                ("script", models.TextField(default="")),
                ("is_main_audio", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TourImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/tour_images")),
                ("caption", models.CharField(default="", max_length=255)),
                ("is_main_image", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TourVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="video/tour_video")),
                ("description", models.TextField(default="")),
                ("script", models.TextField(default="")),
                ("is_main_video", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/user_images")),
                ("is_main_image", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
