# Generated by Django 4.2.1 on 2023-06-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("_MediaAPP", "0001_initial"),
        ("_ToursAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourvideo",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="_ToursAPP.tour",
            ),
        ),
        migrations.AddField(
            model_name="tourimage",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="_ToursAPP.tour",
            ),
        ),
        migrations.AddField(
            model_name="touraudio",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio",
                to="_ToursAPP.tour",
            ),
        ),
        migrations.AddField(
            model_name="stopvideo",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="_ToursAPP.stop",
            ),
        ),
        migrations.AddField(
            model_name="stopvideo",
            name="sub_stop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="video",
                to="_ToursAPP.substop",
            ),
        ),
        migrations.AddField(
            model_name="stopimage",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="_ToursAPP.stop",
            ),
        ),
        migrations.AddField(
            model_name="stopimage",
            name="sub_stop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image",
                to="_ToursAPP.substop",
            ),
        ),
        migrations.AddField(
            model_name="stopaudio",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio",
                to="_ToursAPP.stop",
            ),
        ),
        migrations.AddField(
            model_name="stopaudio",
            name="sub_stop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audio",
                to="_ToursAPP.substop",
            ),
        ),
    ]
