# Generated by Django 4.2.1 on 2023-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_MediaAPP", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourimage",
            name="image_url",
            field=models.URLField(max_length=220, null=True),
        ),
    ]
